In [1]:
from pandas_datareader import wb
import pandas_datareader as pdr
import pandas as pd
import numpy as np

In [4]:
# Download data from World Bank
# Indicators: GDP (current US$), CPI (annual %), Population growth (annual %)
# Countries: Vietnam (VNM), Afghanistan (AFG), Albania (ALB), Anguilla (AIA), Angola (AGO) (Note: Original image had AFE, which is not a valid WB country code, I've used AFG for Afghanistan as a common alternative. If you intended a different country, please provide the correct code.)
# Start year: 1996, End year: 2022
GDP_VN = wb.download(indicator=['NY.GDP.MKTP.CD', 'FP.CPI.TOTL.ZG', 'SP.POP.GROW'],
                     country=['VNM', 'AFG', 'ALB', 'AIA', 'AGO'], # Adjusted based on common WB codes
                     start=1996,
                     end=2025)
GDP_VN

<ipython-input-4-f40ef34ae49c>:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  GDP_VN = wb.download(indicator=['NY.GDP.MKTP.CD', 'FP.CPI.TOTL.ZG', 'SP.POP.GROW'],

                  NY.GDP.MKTP.CD  FP.CPI.TOTL.ZG  SP.POP.GROW
country     year
Afghanistan 1996             NaN             NaN     4.005405
            1997             NaN             NaN     3.804508
            1998             NaN             NaN     3.764687
            1999             NaN             NaN     3.728116
            2000    3.521418e+09             NaN     1.212176
...                          ...             ...          ...
Viet Nam    2020    3.466157e+11        3.220934     0.927434
            2021    3.664748e+11        1.834716     0.868884
            2022    4.103240e+11        3.156507     0.750757
            2023    4.297170e+11        3.252893     0.671429
            2024             NaN        3.621093          NaN

[116 rows x 3 columns]

In [5]:
GDP_VN.colums=['GDP_VN', 'CPI_VN', 'POP_GROW_VN']
GDP_VN

<ipython-input-5-7ac532b86fec>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  GDP_VN.colums=['GDP_VN', 'CPI_VN', 'POP_GROW_VN']

                  NY.GDP.MKTP.CD  FP.CPI.TOTL.ZG  SP.POP.GROW
country     year
Afghanistan 1996             NaN             NaN     4.005405
            1997             NaN             NaN     3.804508
            1998             NaN             NaN     3.764687
            1999             NaN             NaN     3.728116
            2000    3.521418e+09             NaN     1.212176
...                          ...             ...          ...
Viet Nam    2020    3.466157e+11        3.220934     0.927434
            2021    3.664748e+11        1.834716     0.868884
            2022    4.103240e+11        3.156507     0.750757
            2023    4.297170e+11        3.252893     0.671429
            2024             NaN        3.621093          NaN

[116 rows x 3 columns]

In [6]:
GDP_VN = GDP_VN.reset_index()
GDP_VN.head()

       country  year  NY.GDP.MKTP.CD  FP.CPI.TOTL.ZG  SP.POP.GROW
0  Afghanistan  1996             NaN             NaN     4.005405
1  Afghanistan  1997             NaN             NaN     3.804508
2  Afghanistan  1998             NaN             NaN     3.764687
3  Afghanistan  1999             NaN             NaN     3.728116
4  Afghanistan  2000    3.521418e+09             NaN     1.212176

In [10]:
# Save the DataFrame to an Excel file with the specified filename
GDP_VN.to_excel('GDP1.xlsx')

In [ ]:
# Save the DataFrame to an Excel file with the specified filename
GDP_VN.to_excel('GDP1.xlsx')